### ISSUE TITLE
johnvansickle.com IS DOWN

### ISSUE THREAD

**Issue by massens** [jonathanong/heroku-buildpack-ffmpeg-latest#4]
https://www.johnvansickle.com/ffmpeg/ is down
<img width="1263" alt="screen shot 2018-05-16 at 15 36 38" src="https://user-images.githubusercontent.com/15634635/40120703-26846636-5920-11e8-9072-ed94118e273f.png">

**Comment by cblavier** [comment]
ouch ... breaking my production environment :/
any workaround until a permanent solution is found?

**Comment by mikewagz** [comment]
I swapped out the buildpack for another one:

https://github.com/kitcast/buildpack-ffmpeg.git

**Comment by jonathanong** [comment]
anyone want to maintain this? @mikewagz ?

**Comment by jonathanong** [comment]
not using ffmpeg lately and i have no idea what other sources there are out there

**Comment by infovore** [comment]
John Van Sickle has restored access to his [FFMpeg builds](https://johnvansickle.com/ffmpeg/) following enough people contributing to his Patreon.

Worth noting, if you're using this buildpacks in production: you may want to consider contributing to John's Patreon or Paypal in order to support him doing the legwork of compiling ffmpeg and hosting it. Links are at his site.

Anyhow: I think this issue can be closed now.

**Comment by jonathanong** [comment]
@infovore great, thanks.

i would contribute, but unfortunately i don't use this buildpack anymore. again, if anyone would like to maintain this, let me know.
