### ISSUE TITLE
Buildpack not working

### ISSUE THREAD

**Issue by yusjacobs** [jonathanong/heroku-buildpack-ffmpeg-latest#71]
Getting this when deploying in heroku:

Using buildpacks:
       1. https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git
       2. heroku/python
-----> ffmpeg app detected
-----> Installing ffmpeg
       Variable FFMPEG_DOWNLOAD_URL isn't set, using default value
       Downloading https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
       Unable to download ffmpeg: 000

**Comment by stevenmaguire** [comment]
I am seeing the same thing and the ENV variable suggestion is also not working - and I think that is related to the two open PRs here.

**Comment by yusjacobs** [comment]
This started happening today. At the same time the scheduled tests started to fail

**Comment by knagode** [comment]
This is happening in our environment too. 

I can download https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz without issues. I wonder how to resolve this?

**Comment by yusjacobs** [comment]
In the meantime i downloaded the binary from https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz and added it to my repository. I then deployed the app to Heroku and it is working. Just make sure you call the correct PATH to the binary in your code.

**Comment by knagode** [comment]
@yusjacobs 
> Just make sure you call the correct PATH to the binary in your code.

Did you simply put this file in public directory and then use:  
> FFMPEG_DOWNLOAD_URL
to download it?

**Comment by yusjacobs** [comment]
I created a bin folder in my repo and placed the binaries in there, both ffmpeg and ffmprobe. You can download both here: https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz

I then updated my commands like this:

command = ["./bin/ffmpeg", "-ss",.....

**Comment by ekaj2** [comment]
Same issue on my end

**Comment by mindtonic** [comment]
👋🏻

**Comment by sasharevzin** [comment]
> I filed a ticket at heroku support. Will keep you in loop, if there is a suggestion from them.

We need someone with an enterprise account so they can escalate it quickly and not wait for two days for their reply 😭

**Comment by stevenmaguire** [comment]
Thanks @agieche. To clarify, 1) your diagnosis is that johnvansickle.com SSL cert is causing the problem and 2) your fork is only pointing to a different remote URL where an SSL issue is not present, correct?

The thing that I am still not seeing function correctly is the `FFMPEG_DOWNLOAD_URL` env variable. It seems that if I am correct in both of those points, we should not need a new fork of the package, merely a successful path to use `FFMPEG_DOWNLOAD_URL` to point to a new remote URL.

**Comment by ekaj2** [comment]
Just fixed it for my production app as well. Appreciate the quick hotfix @agieche

**Comment by stevenmaguire** [comment]
> I set the ENV variable FFMPEG_DOWNLOAD_URL and restarted dynos and the variable was picked up correctly.

Did you have success setting this variable in the Heroku App (`heroku config ...` etc) or the `app.json` "env" key, or both?

**Comment by stevenmaguire** [comment]
> I added the code to my fork. Then set the env variable within web interface (https://dashboard.heroku.com/apps/my-app-16815/settings) and deployed from CLI. Then, the Env variable was picked up correctly.

Awesome. Thanks!

**Comment by mmaloon** [comment]
With the [Apt buildpack](https://github.com/heroku/heroku-buildpack-apt), when I re-deploy then try to run `ffmpeg -version` in the heroku shell, I receive an error with the message`error while loading shared libraries...`. The deploy also results in a much larger slug size (~250MB with no other buildpacks installed)

Another alternative buildpack is the [heroku-buildpack-activestorage-preview](https://github.com/heroku/heroku-buildpack-activestorage-preview) which also installs the ffmpeg binary.
```
heroku buildpacks:add -i 1 https://github.com/heroku/heroku-buildpack-activestorage-preview
```

This buildpack also seems to fix the segfault issue on heroku-22 stack (https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest/issues/69)

**Comment by jonathanong** [comment]
Thanks @agieche, I added you as a collaborator. I don't use this build pack anymore. If Heroku wants to own this package, let me know!

**Comment by diegotorpoco** [comment]
@agieche What value should the env variable FFMPEG_DOWNLOAD_URL in heroku client should take? many thanks!

**Comment by kayvaninvemo** [comment]
> @agieche What value should the env variable FFMPEG_DOWNLOAD_URL in heroku client should take? many thanks!

Just add a new env variable in heroku->setting 
FFMPEG_DOWNLOAD_URL : https://cookycookstaging.s3.amazonaws.com/ffmpeg-git-amd64-static.tar.xz

and redeploy. Before redeploying I also restarted the dynos, but I guess that it is not necessary.

**Comment by sasharevzin** [comment]
@kayvaninvemo is it safe to use this bucket? it looks very suspicious to me

**Comment by diegotorpoco** [comment]
> > @agieche What value should the env variable FFMPEG_DOWNLOAD_URL in heroku client should take? many thanks!
> 
> Just add a new env variable in heroku->setting FFMPEG_DOWNLOAD_URL : [cookycookstaging.s3.amazonaws.com/ffmpeg-git-amd64-static.tar.xz](https://cookycookstaging.s3.amazonaws.com/ffmpeg-git-amd64-static.tar.xz)
> 
> <img alt="image" width="971" src="https://user-images.githubusercontent.com/74557546/262396632-8bb86a00-3469-4001-aaaa-f1d2e3b221f3.png">
> and redeploy. Before redeploying I also restarted the dynos, but I guess that it is not necessary.

Hey, thanks! In the mean time I tried to use @dzuelke recommendation of using heroku active storage buildpack (https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest/pull/72) 

I have tested in production and it works.

https://github.com/heroku/heroku-buildpack-activestorage-preview.git on heroku buildpacks section

**Comment by kayvaninvemo** [comment]
> @kayvaninvemo is it safe to use this bucket? it looks very suspicious to me

It is not safe, do not use it if it is for an enterprise or a bank. :D

**Comment by palinair** [comment]
Hi! We have had the same problem in our project. Thanks to those who are sharing their valuable solutions!

**Comment by cjreeve** [comment]
Any update on this? Is this for Heroku to fix?

**Comment by cjreeve** [comment]
As a quick work around for hosting the ffmpeg-git-amd64-static.tar.xz file, I copied the file into my development public folder, started ngrok and set the Heroku config var `FFMPEG_DOWNLOAD_URL` to the secure ngrok link to the file.

**Comment by edmorley** [comment]
This issue is not related to Heroku. 

The server's TLS handling seems broken (or there is otherwise some other issue with the server) - local requests fail too depending on the client used, for example this is what I get using curl locally on macOS:

```
$ curl -v https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz -O
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 107.180.57.212:443...
* Connected to johnvansickle.com (107.180.57.212) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
} [322 bytes data]
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* Recv failure: Connection reset by peer
* LibreSSL/3.3.6: error:02FFF036:system library:func(4095):Connection reset by peer
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (35) Recv failure: Connection reset by peer
```

Ultimately I think this buildpack is not a great fit for production workloads, since:
- it sources the binaries from an arbitrary third party server, which (a) could result in supply chain attack issues (a compromise of that site, or even just the domain say expiring could mean all secrets in your app are stolen for example, (b) doesn't seem to be very reliable (this isn't the first time downloads from that site have failed)
- it always downloads "latest" ffmpeg, which means your builds or app could fail at any time, if there is a new major release that is not compatible with your app
- it doesn't use the build cache at all, which is fine for apps using a reliable source for assets (such as an S3 bucket), but less so for downloads from third party sites (as proven by builds failing now due to the hard dependency; plus this buildpack costs the site owner a bunch of bandwidth)

I'd recommend that people either:
1. Switch to https://github.com/heroku/heroku-buildpack-activestorage-preview - which is aimed at Ruby Rails apps, but includes ffmpeg so should work fine. And whilst it's not an "officially supported language buildpack" it's still fairly regularly maintained and uses the same security best practices of the official Heroku buildpacks.
2. Use the APT buildpack
3. Download https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz yourselves, host somewhere secure of your chosing (your own S3 bucket), then reference using the newly fixed `FFMPEG_DOWNLOAD_URL`

**Comment by keShraa** [comment]
Thanks @edmorley for the very detailed explanation 🙏🏻

**Comment by ByTE1974** [comment]
Looks like it's working again!

**Comment by jonathanong** [comment]
If you are using this in production, I would definitely store the binary in my own file storage. you don't want to rely on third party services like this. When I was using this repo, I was using it at an early stage start up.

thanks for the help @agieche, let me know if you can help @edmorley. please email me if any issues come up because I don't code nowadays
